name: Deploy job
on:
  push:
    branches: ["main"]
jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: cd into repo
        uses: actions/checkout@v3
      - name: install dependencies
        run: npm install